# Generated by Django 2.2 on 2019-07-24 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goodmenu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodmenu',
            name='likecount',
        ),
        migrations.RemoveField(
            model_name='goodmenu',
            name='visitcount',
        ),
        migrations.AddField(
            model_name='goodmenu',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='goodmenufavorite_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodmenu',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='goodmenulike_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
