# Generated by Django 2.2 on 2019-07-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodmenu', '0002_auto_20190724_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodmenu',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
