# Generated by Django 2.2 on 2019-07-30 10:03

from django.db import migrations, models
import django.db.models.deletion
import goodmenu.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goodmenu', '0004_remove_goodmenu_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='One Line Description')),
                ('img', goodmenu.fields.ThumbnailImageField(null=True, upload_to='userstar')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='goodmenu',
            name='goodstar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goodstar', to='goodmenu.GoodStar'),
        ),
    ]
