# Generated by Django 2.2 on 2019-07-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodmenu', '0006_auto_20190730_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodmenu',
            name='mapleft',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='goodmenu',
            name='mapright',
            field=models.FloatField(null=True),
        ),
    ]
