# Generated by Django 2.2 on 2019-08-04 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goodmenu', '0007_auto_20190730_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('goodauthorcomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodauthorcomment', to=settings.AUTH_USER_MODEL)),
                ('goodmenucomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodmenu.Goodmenu')),
                ('goodstarcomment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goodstarcomment', to='goodmenu.GoodStar')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
