# Generated by Django 2.2 on 2019-08-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodmenu', '0008_goodcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodmenu',
            name='menulist',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='goodmenu',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
