# Generated by Django 2.2 on 2019-08-07 04:51

from django.db import migrations, models
import django.db.models.deletion
import goodmenu.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goodmenu', '0009_auto_20190807_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img', goodmenu.fields.ThumbnailImageField(upload_to='goodmenu/%Y/%m')),
                ('goodmenuphoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodmenu.Goodmenu')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
