# Generated by Django 2.2 on 2019-08-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodmenu', '0010_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodmenu',
            options={'ordering': ['hit', '-date']},
        ),
        migrations.RemoveField(
            model_name='goodmenu',
            name='detailimg',
        ),
        migrations.RemoveField(
            model_name='goodmenu',
            name='location',
        ),
    ]
