# Generated by Django 2.2 on 2019-08-10 05:08

from django.db import migrations
import goodmenu.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goodmenu', '0012_auto_20190808_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodmenu',
            name='smallimg',
            field=goodmenu.fields.ThumbnailImageField(null=True, upload_to='goodmenu/%Y/%m'),
        ),
    ]
