# Generated by Django 2.2 on 2019-05-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roulettehome', '0002_auto_20190524_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('area', models.CharField(default='송파구', max_length=10)),
                ('star', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('area', models.CharField(default='송파구', max_length=10)),
                ('star', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('area', models.CharField(default='송파구', max_length=10)),
                ('star', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FastFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('area', models.CharField(default='송파구', max_length=10)),
                ('star', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JapaneseFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('area', models.CharField(default='송파구', max_length=10)),
                ('star', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KoreanFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('area', models.CharField(default='송파구', max_length=10)),
                ('star', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WesternFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('area', models.CharField(default='송파구', max_length=10)),
                ('star', models.IntegerField()),
            ],
        ),
    ]
