# Generated by Django 2.2 on 2019-07-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roulettehome', '0003_chinesefood_dessert_drink_fastfood_japanesefood_koreanfood_westernfood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChineseFood',
        ),
        migrations.DeleteModel(
            name='Dessert',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='FastFood',
        ),
        migrations.DeleteModel(
            name='JapaneseFood',
        ),
        migrations.DeleteModel(
            name='KoreanFood',
        ),
        migrations.DeleteModel(
            name='WesternFood',
        ),
    ]
