# Generated by Django 2.2 on 2019-07-22 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usermenu.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='One Line Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='One Line Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('smallbody', models.CharField(max_length=500, null=True)),
                ('body', models.TextField(null=True)),
                ('visitcount', models.IntegerField(default=0)),
                ('star', models.IntegerField(default=3)),
                ('smallimg', usermenu.fields.ThumbnailImageField(upload_to='goodmenu/%Y/%m')),
                ('detailimg', usermenu.fields.ThumbnailImageField(upload_to='goodmenu/%Y/%m')),
                ('location', usermenu.fields.ThumbnailImageField(upload_to='goodmenu/%Y/%m')),
                ('url', models.URLField(null=True, verbose_name='url')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('useralbum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermenu.UserAlbum')),
                ('userarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userarea', to='usermenu.UserArea')),
                ('userauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userauthor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
