# Generated by Django 2.2 on 2019-07-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermenu',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='usermenu',
            name='location',
        ),
        migrations.RemoveField(
            model_name='usermenu',
            name='open_time',
        ),
        migrations.RemoveField(
            model_name='usermenu',
            name='url',
        ),
    ]
