# Generated by Django 2.2 on 2019-07-22 09:20

from django.db import migrations
import usermenu.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0002_auto_20190722_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermenu',
            name='detailimg',
            field=usermenu.fields.ThumbnailImageField(upload_to='usermenu/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='usermenu',
            name='smallimg',
            field=usermenu.fields.ThumbnailImageField(upload_to='usermenu/%Y/%m'),
        ),
    ]
