# Generated by Django 2.2 on 2019-07-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0004_auto_20190724_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermenu',
            name='star',
        ),
    ]
