# Generated by Django 2.2 on 2019-07-27 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0005_remove_usermenu_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='One Line Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='usermenu',
            name='userstar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userstar', to='usermenu.UserStar'),
        ),
    ]
