# Generated by Django 2.2 on 2019-07-27 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0006_auto_20190727_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermenu',
            name='userstar',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='userstar', to='usermenu.UserStar'),
        ),
    ]
