# Generated by Django 2.2 on 2019-07-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0009_auto_20190727_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenu',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
