# Generated by Django 2.2 on 2019-07-30 09:23

from django.db import migrations
import usermenu.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0010_usermenu_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstar',
            name='img',
            field=usermenu.fields.ThumbnailImageField(null=True, upload_to='userstar'),
        ),
    ]
