# Generated by Django 2.2 on 2019-08-04 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0013_remove_usercomment_usermenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='usermenucomment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermenu.UserMenu'),
        ),
    ]
