# Generated by Django 2.2 on 2019-08-04 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0014_auto_20190804_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='userstarcomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userstarcomment', to='usermenu.UserStar'),
        ),
    ]
