# Generated by Django 2.2 on 2019-08-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0015_usercomment_userstarcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermenu',
            options={'ordering': ['hit', '-date']},
        ),
    ]
