# Generated by Django 2.2 on 2019-08-08 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0016_auto_20190807_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermenu',
            options={'ordering': ['-hit', '-date']},
        ),
    ]
