# Generated by Django 2.2 on 2019-08-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0017_auto_20190808_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermenu',
            options={'ordering': ['-hit']},
        ),
    ]
