# Generated by Django 2.2 on 2019-08-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0018_auto_20190808_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='usermenucomment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercomments', to='usermenu.UserMenu'),
        ),
    ]
